install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages("leaflet")
install.packages("remotes")
install.packages("sf")
install.packages("units")
install.packages("udunits2")
install.packages("tigris")
install.packages("tidycensus")
install.packages("patchwork")
install.packages("ggthemes")
remotes::install_github("igraph/rigraph")
install.packages("plotly")
remotes::install_github("jbkunst/highcharter")
remotes::install_github("UrbanInstitute/urbnmapr")

